apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker: {dockerfile: Dockerfile}
    image: gcr.io/qwiklabs-gcp-04-248da7eb1719/tfx_covertype_continuous_training
  local: {push: true, useDockerCLI: true}
  tagPolicy:
    envTemplate: {template: latest}
kind: Config
